/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRobotExplore;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhvalcondition extends AbstractEvhvalcondition { 
	public Evhvalcondition(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
