/* Generated by AN DISI Unibo */ 
package it.unibo.map_keeper;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Map_keeper extends QActorMsgQueue{
	public MsgHandle_Map_keeper(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
