/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.player_retriever;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Player_retriever extends AbstractPlayer_retriever { 
	public Player_retriever(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
