/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.temperature_emitter;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Temperature_emitter extends AbstractTemperature_emitter { 
	public Temperature_emitter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
