/* Generated by AN DISI Unibo */ 
package it.unibo.temperature_emitter;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Temperature_emitter extends QActorMsgQueue{
	public MsgHandle_Temperature_emitter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
