/* Generated by AN DISI Unibo */ 
package it.unibo.ledcontrol;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractLedcontrol extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	//protected String mqttServer = "tcp://localhost:1883";
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractLedcontrol(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/ledcontrol/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/ledcontrol/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("doBlink",doBlink);
	    	stateTab.put("ledOff",ledOff);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "ledcontrol tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_init",0);
	     pr.incNumIter(); 	
	    	String myselfName = "init";  
	    	//bbb
	     msgTransition( pr,myselfName,"ledcontrol_"+myselfName,false,
	          new StateFun[]{stateTab.get("doBlink"), stateTab.get("ledOff") }, 
	          new String[]{"true","M","ledBlink", "true","M","ledOff" },
	          600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun doBlink = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("doBlink",-1);
	    	String myselfName = "doBlink";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("ledBlink");
	    	if( currentMessage != null && currentMessage.msgId().equals("ledBlink") && 
	    		pengine.unify(curT, Term.createTerm("ledBlink")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg = "ledBlinkMsg";
	    		/* Print */
	    		parg =  updateVars( Term.createTerm("ledBlink"), 
	    		                 Term.createTerm("ledBlink"), 
	    			    		 Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) println( parg );
	    	}
	    	it.unibo.ledmock.ledUtil.switchLed( myself  );
	    	//bbb
	     msgTransition( pr,myselfName,"ledcontrol_"+myselfName,false,
	          new StateFun[]{stateTab.get("ledOff"), stateTab.get("doBlink") }, 
	          new String[]{"true","M","ledOff", "true","M","ledBlink" },
	          500, "doBlink" );//msgTransition
	    }catch(Exception e_doBlink){  
	    	 println( getName() + " plan=doBlink WARNING:" + e_doBlink.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//doBlink
	    
	    StateFun ledOff = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("ledOff",-1);
	    	String myselfName = "ledOff";  
	    	it.unibo.ledmock.ledUtil.turnOffLed( myself  );
	    	temporaryStr = "\"LED  OFF\"";
	    	println( temporaryStr );  
	    	//switchTo init
	        switchToPlanAsNextState(pr, myselfName, "ledcontrol_"+myselfName, 
	              "init",false, false, null); 
	    }catch(Exception e_ledOff){  
	    	 println( getName() + " plan=ledOff WARNING:" + e_ledOff.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//ledOff
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
