/* Generated by AN DISI Unibo */ 
package it.unibo.ledcontrol;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledcontrol extends QActorMsgQueue{
	public MsgHandle_Ledcontrol(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
