/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRobotExplore;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhinvcondition extends AbstractEvhinvcondition { 
	public Evhinvcondition(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
