/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.map_keeper;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Map_keeper extends AbstractMap_keeper { 
	public Map_keeper(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
