/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRobotExplore;
import alice.tuprolog.Term;
import it.unibo.contactEvent.interfaces.IEventItem;
import it.unibo.qactors.platform.EventHandlerComponent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.QActorUtils;

public abstract class AbstractEvhvalcondition extends EventHandlerComponent { 
protected IEventItem event;
	public AbstractEvhvalcondition(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, eventIds, outEnvView);
  	}
	@Override
	public void doJob() throws Exception {	}
	
	public void handleCurrentEvent() throws Exception {
		event = this.currentEvent; //AKKA getEventItem();
		if( event == null ) return;
		QActorUtils.sendMsgExecInternal("mind_ctrl","changeEnvCond(ok)");
		//QActorUtils.solveGoal(QActorUtils.getQActor("mind_ctrl").getPrologEngine(),"changeEnvCond(ok)");
	}//handleCurrentEvent
	
	@Override
	protected void handleQActorEvent(IEventItem ev) {
		super.handleQActorEvent(ev);
 		try {
			handleCurrentEvent();
		} catch (Exception e) {
 			e.printStackTrace();
		}
	}//handleQActorEvent
	
}
