/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRobotExplore;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxRobotExplore  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxrobotexplore", "./srcMore/it/unibo/ctxRobotExplore/robotwenvexplore.pl", 
		"./srcMore/it/unibo/ctxRobotExplore/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
